### ISSUE TITLE
deltav speech

### ISSUE THREAD

**Issue by problemSolvingProgramming** [NeilJustice/ZenUnitZenMock#2]
Hello
Can you create a speech-to-text section for Delta V in C # or C?

https://www.youtube.com/watch?v=t778cvQ3dJM

**Comment by NeilJustice** [comment]
Hello Doctor Who,

ZenUnit and MetalMock can confirm the correctness of C++ programs but cannot convert speech to text as spoken to a DeltaV system.

Kind regards,
Neil
